name = "CompetitiveProgramming"
uuid = "e02c9ea3-c857-4d8e-b655-90610a108356"
authors = ["matsueushi <matsueushi@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
