name = "ProgrammingChallenges"
uuid = "78d4c0c3-d9dc-4266-92cc-f3e160f7d9ff"
authors = ["matsueushi <matsueushi@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
